# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: pip install -r examples/PlainPython/ChartsAltair/requirements.txt
    command: trame examples/PlainPython/ChartsAltair/app.py
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
